[repository]
name = "hyprland-plugins"
authors = ["Vaxry","Misterio77","Schweber","fufexan","schievel2","trippwill"]

commit_pins = []

[grimblast]
description = "A Hyprland version of Grimshot"
authors = ["Vaxry","Misterio77"]
output = "grimblast/grimblast"
build = [
    "make all"
]

[hyprprop]
description = "a xprop replacement for hyprland"
authors = ["Vaxry"]
output = "hyprprop/hyprprop"
build = [
    "make all"
]

[hdrop]
description = "This Bash script emulates the main features of tdrop in Hyprland:"
authors = ["Schweber","fufexan"]
output = "hdrop/hdrop"
build = [
    "make all",
]

[scratchpad]
description = "A Bash script that instantly sends focused window to a special workspace named scratchpad and makes it easier to retrieve the window back to the current workspace"
authors = ["niksingh710"]
output = "scratchpad/scratchpad.so"
build = [
    "make all"
]

[shellevents]
description = "Invoke shell functions in response to Hyprland socket2 events"
authors = ["trippwill"]
output = "shellevents/shellevents"
build = [
    "make all"
]

[try_swap_workspace]
description = "Binding to mimic the 'arbitrary workspace on arbitrary monitor behavior"
authors = ["schievel1"]
output = "try_swap_workspace/try_swap_workspace"
build = [
    "make all"
]
